name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get last 8 digits of commit hash
        id: get_hash
        run: |
          chmod +x getHash.sh
          hash=$(./getHash.sh)
          echo "Last 8 digits of commit hash: $hash"
          echo "::set-output name=hash::$hash"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api-demo:${{ steps.get_hash.outputs.hash }} .

      - name: Publish Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api-demo:${{ steps.get_hash.outputs.hash }}
